spring.application.name=publisher

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=hmall
spring.rabbitmq.password=yee23
spring.rabbitmq.virtual-host=/hmall

spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true