spring.application.name=consumer

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=hmall
spring.rabbitmq.password=yee23
spring.rabbitmq.virtual-host=/hmall
spring.rabbitmq.listener.simple.prefetch=1
